proxy:
  enable: false
  http_url: http://127.0.0.1:7890
  https_url:  http://127.0.0.1:7890

dependencies:
  # java: java/current/bin/java
  # scala: scala/current/bin/scala
  # sbt: sbt/current/bin/sbt
  node: /usr/bin/node
  tree-sitter: /usr/bin/tree-sitter
  github-linguist: /usr/local/bin/github-linguist

crawling_language:
  c_cpp  # [c_cpp, java, python]

log_level:
  INFO # [DEBUG, INFO, WARNING, ERROR]

repo_cache_path:
  /storage/cache/agent_cache/repo_cache

llm_cache_path:
 /storage/cache/agent_cache/llm_cache/cache.db

llm_model_path:
 /storage/cache/agent_cache/llm_cache/model

repo_storage_path:
  /storage/result/Part2_result